[2024-09-27T14:45:30.124+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T14:45:30.142+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_costos_ventas.extract_ventas manual__2024-09-27T14:44:32.277884+00:00 [queued]>
[2024-09-27T14:45:30.151+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_costos_ventas.extract_ventas manual__2024-09-27T14:44:32.277884+00:00 [queued]>
[2024-09-27T14:45:30.152+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-27T14:45:30.165+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_ventas> on 2024-09-27 14:44:32.277884+00:00
[2024-09-27T14:45:30.176+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T14:45:30.178+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_costos_ventas', 'extract_ventas', 'manual__2024-09-27T14:44:32.277884+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/RPA_dag.py', '--cfg-path', '/tmp/tmpo97wxclp']
[2024-09-27T14:45:30.179+0000] {standard_task_runner.py:72} INFO - Started process 112 to run task
[2024-09-27T14:45:30.179+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask extract_ventas
[2024-09-27T14:45:30.235+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_costos_ventas.extract_ventas manual__2024-09-27T14:44:32.277884+00:00 [running]> on host 32d53c0d21c3
[2024-09-27T14:45:30.337+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_costos_ventas' AIRFLOW_CTX_TASK_ID='extract_ventas' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T14:44:32.277884+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T14:44:32.277884+00:00'
[2024-09-27T14:45:30.338+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-27T14:45:30.338+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-27T14:45:30.339+0000] {logging_mixin.py:190} INFO - Current task name:extract_ventas state:running start_date:2024-09-27 14:45:30.143291+00:00
[2024-09-27T14:45:30.339+0000] {logging_mixin.py:190} INFO - Dag name:etl_costos_ventas and current dag run status:running
[2024-09-27T14:45:30.339+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T14:45:30.442+0000] {python.py:240} INFO - Done. Returned value was: {'Fecha contabilizacion': {0: Timestamp('2024-02-01 00:00:00'), 1: Timestamp('2024-02-02 00:00:00'), 2: Timestamp('2024-02-03 00:00:00'), 3: Timestamp('2024-02-04 00:00:00'), 4: Timestamp('2024-02-05 00:00:00'), 5: Timestamp('2024-03-07 00:00:00'), 6: Timestamp('2024-03-08 00:00:00'), 7: Timestamp('2024-03-09 00:00:00'), 8: Timestamp('2024-03-10 00:00:00'), 9: Timestamp('2024-06-20 00:00:00'), 10: Timestamp('2024-06-21 00:00:00'), 11: Timestamp('2024-06-22 00:00:00'), 12: Timestamp('2024-06-23 00:00:00'), 13: Timestamp('2024-06-24 00:00:00'), 14: Timestamp('2024-12-12 00:00:00')}, 'Empresa': {0: 'BBU', 1: 'CL', 2: 'CA', 3: 'CL', 4: 'CL', 5: 'CA', 6: 'CL', 7: 'CA', 8: 'CL', 9: 'CA', 10: 'CL', 11: 'CA', 12: 'BBU', 13: 'BBU', 14: 'BBU'}, 'Acumulado Ventas': {0: 200, 1: 100, 2: 150, 3: 300, 4: 112, 5: 165, 6: 385, 7: 26, 8: 302, 9: 409, 10: 431, 11: 25, 12: 445, 13: 363, 14: 173}}
[2024-09-27T14:45:30.450+0000] {xcom.py:690} ERROR - Object of type Timestamp is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-09-27T14:45:30.451+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas._libs.tslibs.timestamps.Timestamp'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3638, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Timestamp is not JSON serializable
[2024-09-27T14:45:30.459+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-27T14:45:30.460+0000] {logging_mixin.py:190} INFO - Task start:2024-09-27 14:45:30.143291+00:00 end:2024-09-27 14:45:30.459324+00:00 duration:0.316033
[2024-09-27T14:45:30.460+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_ventas> dag:<DAG: etl_costos_ventas> dagrun:<DagRun etl_costos_ventas @ 2024-09-27 14:44:32.277884+00:00: manual__2024-09-27T14:44:32.277884+00:00, state:running, queued_at: 2024-09-27 14:45:28.451083+00:00. externally triggered: True>
[2024-09-27T14:45:30.461+0000] {logging_mixin.py:190} INFO - Failure caused by Object of type Timestamp is not JSON serializable
[2024-09-27T14:45:30.461+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_costos_ventas, task_id=extract_ventas, run_id=manual__2024-09-27T14:44:32.277884+00:00, execution_date=20240927T144432, start_date=20240927T144530, end_date=20240927T144530
[2024-09-27T14:45:30.470+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T14:45:30.470+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task extract_ventas (Object of type Timestamp is not JSON serializable; 112)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas._libs.tslibs.timestamps.Timestamp'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3638, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Timestamp is not JSON serializable
[2024-09-27T14:45:30.515+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-27T14:45:30.534+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T14:45:30.537+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
